# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cov2_mxPBF_single <- function(X, Y, a0, b0, log_gamma) {
    .Call(`_hdbcp_cpp_cov2_mxPBF_single`, X, Y, a0, b0, log_gamma)
}

cpd_cov_mxPBF <- function(X, a0, b0, nw, alp, n_threads) {
    .Call(`_hdbcp_cpd_cov_mxPBF`, X, a0, b0, nw, alp, n_threads)
}

simulate_mxPBF_cov <- function(data, a0, b0, nw, alps, n_samples, n_threads) {
    .Call(`_hdbcp_simulate_mxPBF_cov`, data, a0, b0, nw, alps, n_samples, n_threads)
}

cpp_mean2_mxPBF_single <- function(X, Y, log_gamma) {
    .Call(`_hdbcp_cpp_mean2_mxPBF_single`, X, Y, log_gamma)
}

cpd_mean_mxPBF <- function(X, nw, alp, n_threads) {
    .Call(`_hdbcp_cpd_mean_mxPBF`, X, nw, alp, n_threads)
}

simulate_mxPBF_mean <- function(data, nw, alps, n_samples, n_threads) {
    .Call(`_hdbcp_simulate_mxPBF_mean`, data, nw, alps, n_samples, n_threads)
}

cpp_mvrnorm <- function(n, mu, sigma) {
    .Call(`_hdbcp_cpp_mvrnorm`, n, mu, sigma)
}

