# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pre_compute_sums <- function(X, S_ii, S_i, S_ij) {
    invisible(.Call(`_hdbcp_pre_compute_sums`, X, S_ii, S_i, S_ij))
}

cpd_cov_mxPBF <- function(X, S_ii, S_i, S_ij, a0, b0, nw, alp, n_threads) {
    .Call(`_hdbcp_cpd_cov_mxPBF`, X, S_ii, S_i, S_ij, a0, b0, nw, alp, n_threads)
}

simulate_mxPBF_cov <- function(X, S_ii, S_i, S_ij, a0, b0, nw, alps, n_samples, n_threads) {
    .Call(`_hdbcp_simulate_mxPBF_cov`, X, S_ii, S_i, S_ij, a0, b0, nw, alps, n_samples, n_threads)
}

cpd_cov_mxPBF_centered <- function(X, S_ii, S_i, S_ij, a0, b0, nw, maxnw, alp, n_threads) {
    .Call(`_hdbcp_cpd_cov_mxPBF_centered`, X, S_ii, S_i, S_ij, a0, b0, nw, maxnw, alp, n_threads)
}

cpp_mean2_mxPBF_single <- function(X, Y, log_gamma) {
    .Call(`_hdbcp_cpp_mean2_mxPBF_single`, X, Y, log_gamma)
}

cpd_mean_mxPBF <- function(X, nw, alp, n_threads) {
    .Call(`_hdbcp_cpd_mean_mxPBF`, X, nw, alp, n_threads)
}

simulate_mxPBF_mean <- function(data, nw, alps, n_samples, n_threads) {
    .Call(`_hdbcp_simulate_mxPBF_mean`, data, nw, alps, n_samples, n_threads)
}

cpp_mvrnorm <- function(n, mu, sigma) {
    .Call(`_hdbcp_cpp_mvrnorm`, n, mu, sigma)
}

